### ISSUE TITLE
Master is failing

### ISSUE THREAD

**Issue by tbranyen** [5to6/deamdify2#1]
Is this intentional? I'd like to contribute, but with failing tests in master, this isn't a good start.  Can you enable Travis and add a badge to the README once all tests are passing?

**Comment by xjamundx** [comment]
Added you but I'll fix this!

**Comment by xjamundx** [comment]
Are you `tbranyen` on NPM?

**Comment by tbranyen** [comment]
Yup! Awesome, thanks! I'm going to sort through the standing PRs and get as much up-to-date as possible.

**Comment by xjamundx** [comment]
rad. i have 1 thing i'm bringing over which is support for 

`define(['dep'], function() { })` => `require('dep')` (no assignment)

and will get the tests working
give me 30

**Comment by xjamundx** [comment]
```
~/dev/deamdify (master) $ npm owner add tbranyen
+ tbranyen (deamdify2)
```

**Comment by xjamundx** [comment]
Tests pass.
